version: '3.8'

services:
  paperlessrest:
    build:
      context: ./PaperlessREST
      dockerfile: Dockerfile
    container_name: paperlessrest
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    platform: linux/amd64

  paperlessui:
    build:
      context: ./PaperlessUI
      dockerfile: Dockerfile
    container_name: paperlessui
    ports:
      - "80:80"
    depends_on:
      - paperlessrest
    platform: linux/amd64

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=paperless
      - POSTGRES_USER=paperless
      - POSTGRES_DB=paperless_DB

networks:
  paperless-network:
    driver: bridge
