version: '3.8'

services:
  paperlessrest:
    build:
      context: ./PaperlessREST
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - paperless-network

  paperlessui:
    build:
      context: ./PaperlessUI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - paperless-network
    depends_on:
      - paperlessrest

networks:
  paperless-network:
    driver: bridge
