services:
  paperlessrest:
    build:
      context: ./PaperlessREST   # Verzeichnis für das Backend
      dockerfile: Dockerfile     # Dockerfile im PaperlessREST-Verzeichnis
    ports:
      - "8081:8081"
    volumes:
      - ./PaperlessREST:/app
    environment:
      - JAVA_OPTS=-Xmx512m
    platform: linux/amd64