services:
  paperlessrest:
    build:
      context: ./PaperlessREST
      dockerfile: Dockerfile
    container_name: paperlessrest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paperless_DB
      SPRING_DATASOURCE_USERNAME: paperless
      SPRING_DATASOURCE_PASSWORD: paperless
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: paperless
      SPRING_RABBITMQ_PASSWORD: paperless
    depends_on:
      - postgres
      - rabbitmq
      - elasticsearch
      - minio
    volumes:
      - logs:/app/logs
    networks:
      - paperless-network
    platform: linux/amd64

  paperlessui:
    build:
      context: ./PaperlessUI
      dockerfile: Dockerfile
    container_name: paperlessui
    ports:
      - "80:80"
    depends_on:
      - paperlessrest
    volumes:
      - logs:/app/logs
    networks:
      - paperless-network
    platform: linux/amd64

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - logs:/app/logs
    environment:
      - POSTGRES_PASSWORD=paperless
      - POSTGRES_USER=paperless
      - POSTGRES_DB=paperless_DB
    networks:
      - paperless-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9091:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DESIGN: dracula
    networks:
      - paperless-network


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ AMQP Port
      - "15672:15672" # RabbitMQ Management Console
    environment:
      RABBITMQ_DEFAULT_USER: paperless
      RABBITMQ_DEFAULT_PASS: paperless
    volumes:
      - logs:/app/logs
    networks:
      - paperless-network
  
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: paperless
      MINIO_ROOT_PASSWORD: paperless
    volumes:
      - ./minio_data:/data
    networks:
      - paperless-network


  paperlessworker:
    build:
      context: ./PaperlessWORKER
      dockerfile: Dockerfile
    container_name: paperlessworker
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: paperless
      SPRING_RABBITMQ_PASSWORD: paperless
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - minio
      - elasticsearch
    volumes:
      - logs:/app/logs
    networks:
      - paperless-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length
      - logger.level=error
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - paperless-network                


  elasticsearch-ui:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: elasticsearch-ui
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - logger.level=error
    ports:
      - "9092:5601"
    depends_on:
      - elasticsearch
    networks:
      - paperless-network



volumes:
  logs: {}
  es-data:
    driver: local

networks:
  paperless-network:
    driver: bridge
