version: '3'

services:
  PaperlessREST:
    build:
      context: ./PaperlessREST   # Verzeichnis für das Backend
      dockerfile: Dockerfile     # Dockerfile im PaperlessREST-Verzeichnis
    ports:
      - "8081:8081"
    volumes:
      - ./PaperlessREST:/app
    environment:
      - JAVA_OPTS=-Xmx512m
    platform: linux/amd64

  PaperlessWebUI:
    build:
      context: ./PaperlessWebUI  # Verzeichnis für das Frontend
      dockerfile: Dockerfile     # Dockerfile im PaperlessWebUI-Verzeichnis
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://PaperlessREST:8081

networks:
  app-network:
    driver: bridge
