version: '3'

services:
  paperlessrest:
    build:
      context: ./PaperlessREST   # Verzeichnis für das Backend
      dockerfile: Dockerfile     # Dockerfile im PaperlessREST-Verzeichnis
    ports:
      - "8081:8081"
    volumes:
      - ./PaperlessREST:/app
    environment:
      - JAVA_OPTS=-Xmx512m
    platform: linux/amd64
    networks:
      - app-network

  paperlessui:
    build:
      context: ./PaperlessUI     # Verzeichnis für das Frontend
      dockerfile: Dockerfile     # Dockerfile im PaperlessUI-Verzeichnis
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
