version: '3.8'

services:
  paperlessrest:
    build:
      context: ./PaperlessREST
      dockerfile: Dockerfile
    container_name: paperlessrest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paperless_DB
      SPRING_DATASOURCE_USERNAME: paperless
      SPRING_DATASOURCE_PASSWORD: paperless
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: paperless
      SPRING_RABBITMQ_PASSWORD: paperless
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - logs:/app/logs
    networks:
      - paperless-network
    platform: linux/amd64

  paperlessui:
    build:
      context: ./PaperlessUI
      dockerfile: Dockerfile
    container_name: paperlessui
    ports:
      - "80:80"
    depends_on:
      - paperlessrest
    volumes:
      - logs:/app/logs
    networks:
      - paperless-network
    platform: linux/amd64

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - ./PaperlessDB:/docker-entrypoint-initdb.d
      - logs:/app/logs
    environment:
      - POSTGRES_PASSWORD=paperless
      - POSTGRES_USER=paperless
      - POSTGRES_DB=paperless_DB
    networks:
      - paperless-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ AMQP Port
      - "15672:15672" # RabbitMQ Management Console
    environment:
      RABBITMQ_DEFAULT_USER: paperless
      RABBITMQ_DEFAULT_PASS: paperless
    volumes:
      - logs:/app/logs
    networks:
      - paperless-network

  paperlessworker:
    build:
      context: ./PaperlessWORKER
      dockerfile: Dockerfile
    container_name: paperlessworker
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: paperless
      SPRING_RABBITMQ_PASSWORD: paperless
      OCR_ENGINE: tesseract
    depends_on:
      - rabbitmq
    networks:
      - paperless-network

volumes:
  logs: {}

networks:
  paperless-network:
    driver: bridge
