openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8081
    description: Generated server url
paths:
  "/api/documents":
    get:
      tags:
        - document-controller
      summary: Fetches all documents
      operationId: getAllDocuments
      responses:
        '200':
          description: Documents found
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Document"
        '404':
          description: No documents found
          content:
            "*/*":
              schema:
                type: object
    post:
      tags:
        - document-controller
      summary: Uploads a document
      operationId: uploadDocument
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Document uploaded successfully
        '400':
          description: Bad request
          content:
            "*/*":
              schema:
                type: object
        '500':
          description: Internal server error
          content:
            "*/*":
              schema:
                type: object
  "/api/documents/{id}":
    get:
      tags:
        - document-controller
      summary: Fetches a document by ID
      operationId: getDocument
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Document found
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Document"
        '404':
          description: Document not found
          content:
            "*/*":
              schema:
                type: object
components:
  schemas:
    Document:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        contentType:
          type: string
        size:
          type: integer
          format: int64
