### Upload Document
POST http://localhost:8081/api/documents
Content-Type: multipart/form-data; boundary=my-custom-boundary

--my-custom-boundary
Content-Disposition: form-data; name="document"
Content-Type: application/text

Hello World!
--my-custom-boundary
Content-Disposition: form-data; name="file"; filename="pom.xml"
Content-Type: application/pdf

< pom.xml
--my-custom-boundary--


### Get Document by ID
GET http://localhost:8081/api/documents/<put uuid here>
Accept: application/json

### Get All Documents
GET http://localhost:8081/api/documents
Accept: application/json
